import { ColorScheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createPlannerStyles = (colors: ColorScheme, isArabic: boolean = false) => {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    safeArea: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 16,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: colors.text,
    },
    headerActions: {
      flexDirection: 'row',
      gap: 8,
    },
    headerActionBtn: {
      width: 44,
      height: 44,
      borderRadius: colors.radii.md,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    headerBackBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minHeight: 44,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: colors.radii.md,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      ...colors.shadows.sm,
    },
    headerBackText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      paddingHorizontal: 16,
      marginBottom: 12,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginBottom: 16,
    },
    sectionHeaderText: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },

    // Year section
    yearSectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginBottom: 8,
    },
    yearSectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    yearSectionSubtitle: {
      fontSize: 13,
      color: colors.textMuted,
    },
    yearScrollContainer: {
      marginBottom: 16,
    },
    yearCarousel: {
      marginBottom: 16,
    },
    yearPage: {
      width: '100%',
      alignItems: 'center',
      paddingHorizontal: 16,
    },
    deepShadowCard: {
      backgroundColor: colors.surface,
      borderRadius: colors.radii.lg,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      ...colors.shadows.sm,
    },
    yearCard: {
      width: '100%',
      height: 129,
      backgroundColor: colors.surface,
      borderRadius: colors.radii.lg,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: colors.border,
      ...colors.shadows.sm,
    },
    yearCardActive: {
      borderColor: colors.primary,
    },
    yearCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    yearCardTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    yearCardBadge: {
      backgroundColor: colors.primary + '18',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: colors.radii.sm,
    },
    yearStatCard: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bg,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    yearStatValue: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    yearStatLabel: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.textMuted,
    },
    yearTitleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    yearTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
    },
    yearBadge: {
      backgroundColor: colors.primary + '18',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: colors.radii.sm,
    },
    yearBadgeText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.primary,
    },
    yearProgressRow: {
      flexDirection: 'row',
      gap: 16,
    },
    yearProgressCard: {
      flex: 1,
      backgroundColor: colors.bg,
      borderRadius: colors.radii.md,
      padding: 16,
    },
    yearProgressLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
      marginBottom: 8,
    },
    yearProgressValue: {
      fontSize: 28,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    yearProgressSub: {
      fontSize: 11,
      color: colors.textMuted,
    },

    // Month grid
    monthGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: 12,
      gap: 8,
      marginBottom: 24,
    },
    monthCard: {
      width: '100%',
      aspectRatio: 1.2,
      backgroundColor: colors.surface,
      borderRadius: colors.radii.md,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      ...colors.shadows.sm,
    },
    monthCardActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary + '10',
    },
    selectedMonthCard: {
      borderColor: colors.primary,
      backgroundColor: colors.primary + '10',
    },
    monthIndicator: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.primary,
      marginBottom: 4,
    },
    monthName: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
    },
    monthNameActive: {
      color: colors.primary,
    },
    selectedMonthName: {
      color: colors.primary,
      fontWeight: '600',
    },
    monthDayCount: {
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
    },
    monthStats: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 4,
    },
    selectedMonthStats: {
      fontSize: 12,
      color: colors.primary,
      marginTop: 4,
    },

    // Day grid & Calendar
    calendarContainer: {
      paddingHorizontal: 16,
      marginBottom: 0,
    },
    weekdayRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    weekdayCell: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 4,
    },
    weekdayText: {
      fontSize: 11,
      fontWeight: '800',
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    calendarRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    calendarDayCell: {
      flex: 1,
      aspectRatio: 1,
      minHeight: 44,
      marginHorizontal: 3,
    },
    calendarDaySlotEmpty: {
      flex: 1,
      aspectRatio: 1,
      minHeight: 44,
      marginHorizontal: 3,
    },
    dayCard: {
      width: '100%',
      height: '100%',
      backgroundColor: colors.surface,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      position: 'relative',
      paddingVertical: 2,
      ...colors.shadows.sm,
    },
    dayCardEdgeSolid: {
      borderBottomLeftRadius: 3,
      borderBottomRightRadius: 3,
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
    },
    dayCardActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary + '10',
    },
    dayCardToday: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    todayCard: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.35,
      shadowRadius: 6,
      elevation: 4,
    },
    hasTaskCard: {
      borderColor: colors.border,
    },
    dayNumber: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    dayNumberActive: {
      color: colors.primary,
    },
    dayNumberToday: {
      color: colors.primaryText,
    },
    dayText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    todayText: {
      color: colors.primaryText,
      fontWeight: '800',
    },
    dayStats: {
      fontSize: 10,
      color: colors.textMuted,
      marginTop: 1,
    },
    todayStats: {
      fontSize: 10,
      color: colors.primaryText + 'CC',
      fontWeight: '700',
      marginTop: 1,
    },
    dayTaskBadge: {
      marginTop: 2,
      paddingHorizontal: 4,
      paddingVertical: 1,
      borderRadius: 5,
      backgroundColor: colors.primary + '18',
    },
    dayTaskBadgeText: {
      fontSize: 9,
      fontWeight: '800',
      color: colors.primary,
    },
    dayIndicator: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.primary,
      marginTop: 2,
    },

    // Month Details Page Cards
    monthGoalsCardNew: {
      borderRadius: 24,
      padding: 16,
      marginHorizontal: 16,
      marginBottom: 20,
      borderWidth: 1,
      ...colors.shadows.sm,
    },
    monthGoalsHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    monthGoalsTitleText: {
      fontSize: 18,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    monthGoalsPill: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
    },
    monthGoalsPillText: {
      fontSize: 11,
      fontWeight: '800',
    },
    monthStatsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginBottom: 10,
    },
    monthStatCapsule: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      paddingHorizontal: 4,
      borderRadius: 12,
      borderWidth: 1,
      gap: 2,
    },
    monthStatValueText: {
      fontSize: 14,
      fontWeight: '800',
    },
    monthStatLabelText: {
      fontSize: 10,
      fontWeight: '700',
      opacity: 0.85,
    },
    monthProgressContainer: {
      marginTop: 4,
      gap: 6,
    },
    monthProgressBarTrack: {
      height: 6,
      borderRadius: 3,
      overflow: 'hidden',
    },
    monthProgressBarFill: {
      height: '100%',
      borderRadius: 3,
    },
    monthProgressText: {
      fontSize: 11,
      fontWeight: '800',
    },
    monthSummaryCardNew: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 16,
      marginHorizontal: 16,
      marginTop: 0,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: colors.border,
      ...colors.shadows.sm,
    },
    monthSummaryHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    monthSummaryTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.2,
    },
    monthSummaryItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 12,
      marginBottom: 6,
      borderWidth: 1,
    },
    monthSummaryItemText: {
      fontSize: 13,
      fontWeight: '700',
      flex: 1,
    },
    monthSummaryItemCount: {
      fontSize: 13,
      fontWeight: '800',
    },

    // Day detail & Daily View Redesign
    specificDayHeaderNew: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 4,
      marginBottom: 16,
    },
    specificDayDateGroup: {
      flex: 1,
    },
    specificDayTitleNew: {
      fontSize: 24,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.5,
    },
    specificDayWeekdayPill: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
      backgroundColor: colors.primary + '18',
      marginTop: 4,
    },
    specificDayWeekdayText: {
      fontSize: 11,
      fontWeight: '800',
      color: colors.primary,
    },
    specificDayTaskCountBadge: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      ...colors.shadows.sm,
    },
    specificDayTaskCountNumber: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
    },
    specificDayTaskCountLabel: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.textMuted,
    },

    // Day Quick Lists
    dayListsRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      gap: 8,
      marginBottom: 16,
    },
    dayListCardModern: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
      ...colors.shadows.sm,
    },
    dayListCardIconWrapModern: {
      width: 32,
      height: 32,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    dayListCardTitleModern: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 2,
    },
    dayListCardCountModern: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.textMuted,
    },

    // Day Section Headers & Collapsibles
    dayCollapsibleHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      marginBottom: 8,
    },
    dayCollapsibleTitleGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    dayCollapsibleTitleText: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.text,
    },
    dayCollapsibleBadge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 8,
    },
    dayCollapsibleBadgeText: {
      fontSize: 11,
      fontWeight: '800',
    },

    // Day Task Items (List Card Style)
    dayTaskCardModern: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 12,
      marginHorizontal: 16,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
      ...colors.shadows.sm,
    },
    dayTaskCardModernActive: {
      borderColor: colors.primary,
      borderLeftWidth: 3,
      borderLeftColor: colors.primary,
    },
    dayTaskCardDone: {
      opacity: 0.65,
    },
    dayTaskCheckBtn: {
      width: 32,
      height: 32,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    dayTaskContentCol: {
      flex: 1,
    },
    dayTaskTitleText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      lineHeight: 18,
    },
    dayTaskTitleDone: {
      textDecorationLine: 'line-through',
      color: colors.textMuted,
    },
    dayTaskMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 4,
    },
    dayTaskTimeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      backgroundColor: colors.primary + '14',
    },
    dayTaskTimeChipText: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.primary,
    },
    dayTaskPriorityBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      backgroundColor: colors.danger + '18',
    },
    dayTaskPriorityText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.danger,
    },

    // Reminders & Notes Cards in Day View
    dayReminderItemCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 12,
      marginHorizontal: 16,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
      ...colors.shadows.sm,
    },
    dayReminderIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.danger + '15',
      justifyContent: 'center',
      alignItems: 'center',
    },
    dayNoteItemCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 12,
      marginHorizontal: 16,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
      ...colors.shadows.sm,
    },
    dayNoteIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.primary + '15',
      justifyContent: 'center',
      alignItems: 'center',
    },

    // Input container in Day View
    dayInputWrapper: {
      marginHorizontal: 16,
      marginVertical: 12,
    },

    // Day detail
    specificDayHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginBottom: 12,
    },
    specificDayTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    specificDaySubtitle: {
      fontSize: 13,
      color: colors.textMuted,
    },
    dayDetailContainer: {
      paddingHorizontal: 16,
      paddingBottom: 48,
    },
    dayDetailHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    dayDetailTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    dayDetailDate: {
      fontSize: 13,
      color: colors.textMuted,
    },
    dayListsSection: {
      marginBottom: 16,
    },
    dayListsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    dayListCard: {
      width: '47%',
      backgroundColor: colors.surface,
      borderRadius: colors.radii.md,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
    },
    dayListCardIconWrap: {
      width: 32,
      height: 32,
      borderRadius: colors.radii.sm,
      backgroundColor: colors.primary + '12',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    dayListCardTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    dayListCardCount: {
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
    },
    daySectionCard: {
      backgroundColor: colors.surface,
      borderRadius: colors.radii.lg,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 12,
      ...colors.shadows.sm,
    },
    daySectionCardTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 12,
    },
    dayListItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      gap: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    dayListItemLast: {
      borderBottomWidth: 0,
    },
    dayListItemText: {
      flex: 1,
      fontSize: 14,
      color: colors.text,
    },
    dayListItemDone: {
      textDecorationLine: 'line-through',
      color: colors.textMuted,
    },
    dayListAddBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 10,
    },
    dayListAddText: {
      fontSize: 13,
      color: colors.textMuted,
      fontWeight: '600',
    },
    horizontalGridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    gridTaskItem: {
      width: '45%',
      backgroundColor: colors.surface,
      borderRadius: colors.radii.md,
      padding: 12,
      marginRight: 8,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    taskItemText: {
      fontSize: 13,
      color: colors.text,
    },
    dayTasksSection: {
      marginBottom: 8,
    },
    dayTasksHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    dayTasksHeaderText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    monthGoalsCard: {
      marginHorizontal: 16,
      backgroundColor: colors.surface,
      borderRadius: colors.radii.lg,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      ...colors.shadows.sm,
      marginBottom: 16,
    },
    monthGoalsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    monthGoalsTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    monthGoalsStats: {
      flexDirection: 'row',
      gap: 16,
    },
    monthGoalsStat: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    monthGoalsStatText: {
      fontSize: 13,
      color: colors.textMuted,
    },
    monthGoalsEmpty: {
      fontSize: 13,
      color: colors.textMuted,
      textAlign: 'center',
      paddingVertical: 16,
    },
    emptyState: {
      paddingVertical: 40,
      alignItems: 'center',
    },
    emptyStateText: {
      fontSize: 14,
      color: colors.textMuted,
      marginTop: 8,
    },
    addDayTaskContainer: {
      marginHorizontal: 16,
      marginBottom: 16,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },

    // --- Modal Base Styles ---
    modalHandle: {
      width: 40,
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginBottom: 20,
    },
    modalInput: {
      backgroundColor: colors.bg,
      borderRadius: colors.radii.md,
      padding: 14,
      fontSize: 15,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalPrimaryBtn: {
      backgroundColor: colors.primary,
      borderRadius: colors.radii.md,
      padding: 16,
      alignItems: 'center',
      marginTop: 20,
    },
    modalPrimaryBtnText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.primaryText,
    },
    modalSecondaryBtn: {
      padding: 14,
      alignItems: 'center',
      marginTop: 8,
    },
    modalSecondaryBtnText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textMuted,
    },

    // --- List Modal Styles ---
    listModalSheet: {
      backgroundColor: colors.surfaceHigh || colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 20,
      paddingBottom: 40,
      maxHeight: '90%',
    },
    listModalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    listModalSubtitle: {
      fontSize: 14,
      color: colors.textMuted,
      marginBottom: 16,
    },
    emptyListContainer: {
      paddingVertical: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyListText: {
      fontSize: 15,
      color: colors.textMuted,
      marginTop: 12,
    },
    listItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      gap: 12,
    },
    listItemText: {
      flex: 1,
      fontSize: 15,
      color: colors.text,
    },
    bulletDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.textMuted,
    },
    toggleHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      gap: 12,
    },
    toggleContent: {
      paddingLeft: 32,
      paddingRight: 12,
      paddingBottom: 12,
    },
    toggleContentText: {
      fontSize: 14,
      color: colors.textMuted,
      lineHeight: 20,
    },
    listAddRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.bg,
      borderRadius: colors.radii.md,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
      marginTop: 8,
    },
    listInput: {
      flex: 1,
      minHeight: 44,
      fontSize: 15,
      color: colors.text,
      paddingVertical: 12,
    },
    listAddButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      borderWidth: 1,
      borderColor: colors.border,
      borderStyle: 'dashed',
      borderRadius: colors.radii.md,
      marginTop: 16,
      gap: 8,
    },
    listAddButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.primary,
    },
  });

  return styles;
};
