import { ColorScheme, getNeoShadow } from "@/hooks/useTheme";
import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get('window');
const gapSize = 12;
const paddingHorizontal = 20;
const totalPadding = paddingHorizontal * 2;
// Subtracting border width (approx 3-4px total) and a small buffer to ensure 3 columns
const cardWidth = (width - totalPadding - (gapSize * 2) - 6) / 3;
const gridCardWidth = (width - 48 - gapSize) / 2; // 2 columns with padding 24*2 + one gap


export const createPlannerStyles = (colors: ColorScheme, isArabic: boolean = false) => {
  const raised = getNeoShadow(colors, 'raised', isArabic);
  const flat = getNeoShadow(colors, 'flat', isArabic);
  const inset = getNeoShadow(colors, 'inset', isArabic);
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    safeArea: {
      flex: 1,
    },
    header: {
      paddingHorizontal: 24,
      paddingTop: 32,
      paddingBottom: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerTitle: {
      fontSize: isArabic ? 28 : 24,
      fontWeight: '800',
      color: colors.text,
    },
    monthGrid: {
      paddingHorizontal: paddingHorizontal,
      paddingVertical: 20,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: gapSize,
    },
    monthCard: {
      width: cardWidth,
      height: cardWidth,
      borderRadius: 28,
      justifyContent: 'center',
      alignItems: 'center',
      ...raised,
    },
    selectedMonthCard: {
      ...inset,
      borderRadius: 28,
    },
    monthName: {
      fontSize: isArabic ? 18 : 16,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 4,
      letterSpacing: isArabic ? 0 : 0.5,
    },
    selectedMonthName: {
      color: colors.primary,
      opacity: 0.9,
    },
    monthStats: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    selectedMonthStats: {
      color: colors.primary,
      opacity: 0.7,
    },
    monthIndicator: {
      position: 'absolute',
      top: 10,
      ...(isArabic ? { left: 10 } : { right: 10 }),
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.5,
      shadowRadius: 3,
      elevation: 2,
    },
    dayGrid: {
      paddingHorizontal: paddingHorizontal,
      paddingVertical: 20,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: gapSize,
    },
    dayCard: {
      width: cardWidth,
      height: cardWidth * 1.1,
      borderRadius: 26,
      backgroundColor: raised.backgroundColor,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 3,
    },
    hasTaskCard: {
      borderColor: colors.primary + '40',
      backgroundColor: colors.primary + '08',
    },
    todayCard: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
      elevation: 4,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    dayText: {
      fontSize: isArabic ? 22 : 20,
      fontWeight: '800',
      color: colors.surfaceText,
      marginBottom: 2,
    },
    todayText: {
      color: colors.primaryText,
    },
    dayStats: {
        fontSize: 10,
        fontWeight: '700',
        color: colors.textMuted,
        textTransform: 'uppercase',
    },
    todayStats: {
        color: colors.primaryText + 'CC',
    },
    taskDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.primary,
      position: 'absolute',
      bottom: 8,
    },
    dayListContainer: {
      flex: 1,
      marginTop: 10,
    },
    specificDayHeader: {
      paddingHorizontal: 24,
      marginBottom: 20,
    },
    specificDayTitle: {
      fontSize: isArabic ? 32 : 28,
      fontWeight: '800',
      color: colors.text,
    },
    specificDaySubtitle: {
      fontSize: 14,
      color: colors.textMuted,
      marginTop: 4,
    },
    dayItem: {
      backgroundColor: raised.backgroundColor,
      marginHorizontal: 20,
      marginBottom: 12,
      borderRadius: 26,
      padding: 18,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.06,
      shadowRadius: 16,
      elevation: 3,
    },
    dayHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    dayTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    taskCount: {
      fontSize: 12,
      color: colors.textMuted,
      fontWeight: '500',
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      paddingHorizontal: 24,
    },
    backText: {
      marginLeft: 8,
      fontSize: 16,
      fontWeight: '600',
      color: colors.primary,
    },
    taskItem: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.primary + "0C",
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 12,
      width: '92%',
      alignSelf: 'center',
      marginBottom: 8,
    },
    taskItemText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '500',
      color: colors.text,
    },
    emptyMonthText: {
      textAlign: 'center',
      marginTop: 40,
      color: colors.textMuted,
      fontSize: 16,
    },
    addDayTaskContainer: {
        paddingHorizontal: 24,
        marginTop: 20,
    },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: 24,
      gap: gapSize,
    },
    gridTaskItem: {
      width: gridCardWidth,
      height: 145,
      borderRadius: 26,
      padding: 16,
      flexDirection: 'column',
      justifyContent: 'space-between',
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.06,
      shadowRadius: 14,
      elevation: 3,
    },
    gridTaskItemText: {
      fontSize: 16,
      fontWeight: '600',
      writingDirection: 'auto',
      fontFamily: Platform.OS === 'ios' ? 'Inter' : 'sans-serif-medium',
    },
    horizontalGridContainer: {
      flexDirection: 'column',
      flexWrap: 'wrap',
      paddingHorizontal: 24,
      height: 310, // 145 * 2 + 20 gap
      gap: 12,
    },

    // Yearly Goals & Achievements
    yearSectionHeader: {
      paddingHorizontal: 24,
      marginTop: 8,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    yearSectionTitle: {
      fontSize: isArabic ? 20 : 18,
      fontWeight: '800',
      color: colors.text,
    },
    yearSectionSubtitle: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
      backgroundColor: colors.primary + '15',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      overflow: 'hidden',
    },
    yearScrollContainer: {
      paddingBottom: 4,
    },
    yearCard: {
      width: width - 32,
      marginHorizontal: 16,
      borderRadius: 28,
      padding: 20,
      ...raised,
      minHeight: 180,
      justifyContent: 'center',
    },
    yearCardActive: {
      borderWidth: 2,
      borderColor: colors.primary,
    },
    yearCardHeader: {
      flexDirection: isArabic ? 'row-reverse' : 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    yearCardTitle: {
      fontSize: isArabic ? 28 : 24,
      fontWeight: '800',
      color: colors.text,
    },
    yearCardBadge: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.primaryText,
      backgroundColor: colors.primary,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      overflow: 'hidden',
    },
    yearItemRow: {
      flexDirection: isArabic ? 'row-reverse' : 'row',
      alignItems: 'center',
      backgroundColor: colors.bg,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: 8,
      gap: 10,
    },
    yearItemText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    yearItemTextCompleted: {
      textDecorationLine: 'line-through',
      color: colors.textMuted,
    },
    yearInputContainer: {
      flexDirection: isArabic ? 'row-reverse' : 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 4,
    },
    yearInput: {
      flex: 1,
      backgroundColor: colors.bg,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      textAlign: isArabic ? 'right' : 'left',
    },
    yearAddButton: {
      width: 40,
      height: 40,
      borderRadius: 14,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    yearEmptyText: {
      textAlign: 'center',
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '500',
      marginVertical: 16,
    },
    achievementCard: {
      marginHorizontal: 20,
      marginBottom: 20,
      borderRadius: 28,
      padding: 20,
      ...raised,
    },
    achievementHeader: {
      flexDirection: isArabic ? 'row-reverse' : 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    achievementTitle: {
      fontSize: isArabic ? 20 : 18,
      fontWeight: '800',
      color: colors.text,
    },
    achievementBadge: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.success,
      backgroundColor: colors.success + '15',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 10,
      overflow: 'hidden',
    },
    achievementItemRow: {
      flexDirection: isArabic ? 'row-reverse' : 'row',
      alignItems: 'center',
      backgroundColor: colors.bg,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: 8,
      gap: 10,
    },
    achievementItemText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    achievementEmptyText: {
      textAlign: 'center',
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: '500',
      marginVertical: 16,
    },
    achievementInputContainer: {
      flexDirection: isArabic ? 'row-reverse' : 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 4,
    },
    achievementInput: {
      flex: 1,
      backgroundColor: colors.bg,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      textAlign: isArabic ? 'right' : 'left',
    },
    achievementAddButton: {
      width: 40,
      height: 40,
      borderRadius: 14,
      backgroundColor: colors.success,
      justifyContent: 'center',
      alignItems: 'center',
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginHorizontal: 24,
      marginVertical: 16,
    },

    // ── Day Lists Section ────────────────────────────────────────────────────
    dayListsSection: {
      paddingHorizontal: 20,
      marginTop: 20,
      marginBottom: 20,
    },
    dayListsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    dayListCard: {
      width: (width - 40 - 12) / 2,
      borderRadius: 22,
      padding: 16,
      backgroundColor: raised.backgroundColor,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    dayListCardIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
    },
    dayListCardTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 4,
    },
    dayListCardCount: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
    },

    // ── List Modal ───────────────────────────────────────────────────────────
    modalHandle: {
      width: 44,
      height: 5,
      borderRadius: 4,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginBottom: 20,
    },
    listModalSheet: {
      backgroundColor: raised.backgroundColor,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      paddingTop: 12,
      paddingHorizontal: 24,
      paddingBottom: 40,
      maxHeight: '90%',
    },
    listModalTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 4,
    },
    listModalSubtitle: {
      fontSize: 13,
      color: colors.textMuted,
      marginBottom: 20,
    },
    listItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary + '0C',
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      gap: 12,
      width: '100%',
      marginBottom: 8,
    },
    listItemText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '500',
      color: colors.text,
    },
    bulletDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary,
    },
    toggleHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    toggleContent: {
      marginTop: 8,
      marginLeft: 34,
      padding: 12,
      backgroundColor: colors.bg,
      borderRadius: 12,
    },
    toggleContentText: {
      fontSize: 13,
      color: colors.textMuted,
      lineHeight: 20,
    },
    listAddRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: raised.backgroundColor,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginTop: 8,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    listInput: {
      flex: 1,
      fontSize: 16,
      color: colors.text,
      marginLeft: 12,
      fontWeight: '500',
      padding: 0,
    },
    listAddButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 16,
      gap: 12,
      width: '100%',
    },
    listAddButtonText: {
      fontSize: 16,
      fontWeight: '500',
      color: colors.primary,
    },
    emptyListContainer: {
      paddingVertical: 40,
      alignItems: 'center',
      gap: 8,
    },
    emptyListText: {
      fontSize: 14,
      color: colors.textMuted,
      fontWeight: '500',
    },
    modalPrimaryBtn: {
      backgroundColor: colors.primary,
      borderRadius: 20,
      paddingVertical: 16,
      alignItems: 'center',
    },
    modalPrimaryBtnText: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.primaryText,
    },
    modalSecondaryBtn: {
      alignItems: 'center',
      paddingVertical: 14,
    },
    modalSecondaryBtnText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textMuted,
    },
    modalInput: {
      backgroundColor: colors.bg,
      borderRadius: 18,
      paddingHorizontal: 16,
      paddingVertical: 13,
      fontSize: 15,
      color: colors.text,
      marginBottom: 16,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 6,
      elevation: 1,
    },
  });
};
